# Конфигурационный файл для обучения модели детекции СИЗ с OBB (Oriented Bounding Box)
# Поддержка rotated bounding boxes для объектов под наклоном
# Классы: защитная каска (оранжевая или белая) и сигнальный жилет
# Оптимизировано для очень маленьких объектов и высокого угла обзора
#
# Формат аннотаций OBB (в файлах .txt):
# class_id x1 y1 x2 y2 x3 y3 x4 y4
# где (x1,y1), (x2,y2), (x3,y3), (x4,y4) - 4 точки углов rotated box (нормализованные координаты 0-1)

# Путь к корневой директории датасета
path: ./data

# Пути к изображениям
train: images/train
val: images/val

# Количество классов
nc: 2

# Имена классов
names:
  0: helmet  # Защитная каска (оранжевая или белая)
  1: vest    # Сигнальный жилет

